// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/Remrinrin/bot-youmiya-main-go/internal/dao/internal"
)

// onebot11OnebotMessagesDao is the data access object for the table onebot_messages.
// You can define custom methods on it to extend its functionality as needed.
type onebot11OnebotMessagesDao struct {
	*internal.Onebot11OnebotMessagesDao
}

var (
	// Onebot11OnebotMessages is a globally accessible object for table onebot_messages operations.
	Onebot11OnebotMessages = onebot11OnebotMessagesDao{internal.NewOnebot11OnebotMessagesDao()}
)

// Add your custom methods and functionality below.
