// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package onebot

import (
	"github.com/Remrinrin/bot-youmiya-main-go/api/onebot"
)

type ControllerV1 struct{}

func NewV1() onebot.IOnebotV1 {
	return &ControllerV1{}
}
